# Generated by Django 5.2.7 on 2025-10-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconsole', '0002_alter_kbeuserextension_kbe_bin_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbeuserextension',
            name='kbe_bin_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='KBE_BIN_PATH'),
        ),
        migrations.AlterField(
            model_name='kbeuserextension',
            name='kbe_res_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='KBE_RES_PATH'),
        ),
    ]
