# Generated by Django 5.2.7 on 2025-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '服务器运行配置',
                'verbose_name_plural': '服务器运行配置',
                'managed': False,
            },
        ),
    ]
