# Generated by Django 5.2.7 on 2025-10-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='config',
            field=models.TextField(default='', help_text='配置(JSON)', max_length=32768, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='名称', max_length=128, unique=True, verbose_name='配置名'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='sys_user',
            field=models.CharField(default='', help_text='系统账号', max_length=128, verbose_name='系统账号'),
        ),
    ]
